### ISSUE TITLE
ch_cpuinfo.sh: line 902: cesho: command not found

### ISSUE THREAD

**Issue by yslin1995** [daxiguaya/ch_cpuinfo#1]
https://github.com/daxiguaya/ch_cpuinfo/blob/b9e583326639e93ac49ecd120c6ce275d21fb7da/ch_cpuinfo.sh#L902

cesho -> cecho

**Comment by daxiguaya** [comment]
There was an issue with the original shell script. Thank you for your discovery. It has been modified
